export interface TemplateColors {
    headerBg: string;
    headerText: string;
    bodyBg: string;
    bodyText: string;
    headingColor: string;
    headingBorder: string;
    subText: string;
    skillBg: string;
    skillText: string;
    skillBorder: string;
    linkColor: string;
    accentColor: string;
    separatorColor: string;
    sidebarBg?: string;
    sidebarText?: string;
}

export type LayoutType = "classic" | "sidebar-left" | "compact" | "modern-split" | "elegant-border";

export interface ResumeTemplateConfig {
    id: string;
    name: string;
    description: string;
    colors: TemplateColors;
    previewGradient: string;
    layout: LayoutType;
}

export const RESUME_TEMPLATES: ResumeTemplateConfig[] = [
    // ── CLASSIC LAYOUT (centered header, 8/4 grid) ──
    {
        id: "elite-gold",
        name: "Elite Gold",
        description: "Gold standard — centered header, classic 2-column",
        previewGradient: "linear-gradient(135deg, #000000 0%, #D4AF37 100%)",
        layout: "classic",
        colors: {
            headerBg: "#000000",
            headerText: "#D4AF37",
            bodyBg: "#ffffff",
            bodyText: "#000000",
            headingColor: "#000000",
            headingBorder: "#D4AF37",
            subText: "#4a4a4a",
            skillBg: "rgba(212, 175, 55, 0.05)",
            skillText: "#000000",
            skillBorder: "#D4AF37",
            linkColor: "#000000",
            accentColor: "#D4AF37",
            separatorColor: "#f0f0f0",
        },
    },
    {
        id: "classic-navy",
        name: "Classic Navy",
        description: "Traditional navy & gold — centered header, classic grid",
        previewGradient: "linear-gradient(135deg, #1e3a5f 0%, #D4AF37 100%)",
        layout: "classic",
        colors: {
            headerBg: "#1e3a5f",
            headerText: "#ffffff",
            bodyBg: "#ffffff",
            bodyText: "#000000",
            headingColor: "#1e3a5f",
            headingBorder: "#D4AF37",
            subText: "#4a5568",
            skillBg: "#f8f9fa",
            skillText: "#1a202c",
            skillBorder: "#D4AF37",
            linkColor: "#1e3a5f",
            accentColor: "#D4AF37",
            separatorColor: "#e2e8f0",
        },
    },
    {
        id: "ruby-classic",
        name: "Ruby Classic",
        description: "Bold red — centered header, classic grid",
        previewGradient: "linear-gradient(135deg, #991b1b 0%, #fca5a5 100%)",
        layout: "classic",
        colors: {
            headerBg: "#7f1d1d",
            headerText: "#fef2f2",
            bodyBg: "#ffffff",
            bodyText: "#1f2937",
            headingColor: "#7f1d1d",
            headingBorder: "#ef4444",
            subText: "#6b7280",
            skillBg: "#fef2f2",
            skillText: "#991b1b",
            skillBorder: "#fecaca",
            linkColor: "#dc2626",
            accentColor: "#ef4444",
            separatorColor: "#fee2e2",
        },
    },

    // ── SIDEBAR LEFT LAYOUT (colored sidebar on the left with skills/edu, main content right) ──
    {
        id: "sidebar-emerald",
        name: "Emerald Sidebar",
        description: "Deep green sidebar with skills & education",
        previewGradient: "linear-gradient(to right, #064e3b 40%, #ffffff 40%)",
        layout: "sidebar-left",
        colors: {
            headerBg: "#064e3b",
            headerText: "#ecfdf5",
            bodyBg: "#ffffff",
            bodyText: "#064e3b",
            headingColor: "#064e3b",
            headingBorder: "#10b981",
            subText: "#4b5563",
            skillBg: "rgba(16, 185, 129, 0.15)",
            skillText: "#ecfdf5",
            skillBorder: "#6ee7b7",
            linkColor: "#047857",
            accentColor: "#10b981",
            separatorColor: "#d1fae5",
            sidebarBg: "#064e3b",
            sidebarText: "#ecfdf5",
        },
    },
    {
        id: "sidebar-ocean",
        name: "Ocean Sidebar",
        description: "Deep blue sidebar — professional lateral layout",
        previewGradient: "linear-gradient(to right, #0c4a6e 40%, #ffffff 40%)",
        layout: "sidebar-left",
        colors: {
            headerBg: "#0c4a6e",
            headerText: "#e0f2fe",
            bodyBg: "#ffffff",
            bodyText: "#0f172a",
            headingColor: "#0c4a6e",
            headingBorder: "#06b6d4",
            subText: "#64748b",
            skillBg: "rgba(14, 165, 233, 0.2)",
            skillText: "#e0f2fe",
            skillBorder: "#7dd3fc",
            linkColor: "#0284c7",
            accentColor: "#0ea5e9",
            separatorColor: "#e0f2fe",
            sidebarBg: "#0c4a6e",
            sidebarText: "#e0f2fe",
        },
    },
    {
        id: "sidebar-purple",
        name: "Lavender Sidebar",
        description: "Rich purple sidebar — creative professional look",
        previewGradient: "linear-gradient(to right, #581c87 40%, #ffffff 40%)",
        layout: "sidebar-left",
        colors: {
            headerBg: "#581c87",
            headerText: "#faf5ff",
            bodyBg: "#ffffff",
            bodyText: "#2e1065",
            headingColor: "#581c87",
            headingBorder: "#a855f7",
            subText: "#6b7280",
            skillBg: "rgba(168, 85, 247, 0.2)",
            skillText: "#faf5ff",
            skillBorder: "#ddd6fe",
            linkColor: "#7e22ce",
            accentColor: "#a855f7",
            separatorColor: "#f3e8ff",
            sidebarBg: "#581c87",
            sidebarText: "#faf5ff",
        },
    },

    // ── COMPACT LAYOUT (single column, no sidebar, dense) ──
    {
        id: "compact-minimal",
        name: "Compact White",
        description: "Single-column, ultra-clean minimal layout",
        previewGradient: "linear-gradient(135deg, #ffffff 0%, #000000 100%)",
        layout: "compact",
        colors: {
            headerBg: "#ffffff",
            headerText: "#000000",
            bodyBg: "#ffffff",
            bodyText: "#000000",
            headingColor: "#000000",
            headingBorder: "#000000",
            subText: "#555555",
            skillBg: "#f3f4f6",
            skillText: "#000000",
            skillBorder: "#d1d5db",
            linkColor: "#000000",
            accentColor: "#000000",
            separatorColor: "#e5e7eb",
        },
    },
    {
        id: "compact-slate",
        name: "Compact Slate",
        description: "Cool-gray single-column — corporate clean",
        previewGradient: "linear-gradient(135deg, #334155 0%, #cbd5e1 100%)",
        layout: "compact",
        colors: {
            headerBg: "#1e293b",
            headerText: "#f1f5f9",
            bodyBg: "#ffffff",
            bodyText: "#1f2937",
            headingColor: "#334155",
            headingBorder: "#64748b",
            subText: "#9ca3af",
            skillBg: "#f8fafc",
            skillText: "#334155",
            skillBorder: "#cbd5e1",
            linkColor: "#475569",
            accentColor: "#64748b",
            separatorColor: "#e2e8f0",
        },
    },
    {
        id: "compact-sunset",
        name: "Compact Sunset",
        description: "Warm orange single-column — friendly and modern",
        previewGradient: "linear-gradient(135deg, #ea580c 0%, #fbbf24 100%)",
        layout: "compact",
        colors: {
            headerBg: "#fff7ed",
            headerText: "#9a3412",
            bodyBg: "#ffffff",
            bodyText: "#1c1917",
            headingColor: "#9a3412",
            headingBorder: "#ea580c",
            subText: "#78716c",
            skillBg: "#fff7ed",
            skillText: "#9a3412",
            skillBorder: "#fed7aa",
            linkColor: "#c2410c",
            accentColor: "#ea580c",
            separatorColor: "#ffedd5",
        },
    },

    // ── MODERN SPLIT LAYOUT (left-aligned header banner, equal 2-column body) ──
    {
        id: "split-tech",
        name: "Tech Split",
        description: "Developer-focused — left banner header, equal columns",
        previewGradient: "linear-gradient(135deg, #0f172a 0%, #10b981 100%)",
        layout: "modern-split",
        colors: {
            headerBg: "#0f172a",
            headerText: "#10b981",
            bodyBg: "#ffffff",
            bodyText: "#0f172a",
            headingColor: "#0f172a",
            headingBorder: "#10b981",
            subText: "#64748b",
            skillBg: "#ecfdf5",
            skillText: "#065f46",
            skillBorder: "#6ee7b7",
            linkColor: "#059669",
            accentColor: "#10b981",
            separatorColor: "#f1f5f9",
        },
    },
    {
        id: "split-creative",
        name: "Creative Split",
        description: "Bold pink/purple — artistic equal-column split",
        previewGradient: "linear-gradient(135deg, #db2777 0%, #7c3aed 100%)",
        layout: "modern-split",
        colors: {
            headerBg: "#7c3aed",
            headerText: "#ffffff",
            bodyBg: "#ffffff",
            bodyText: "#1e1b4b",
            headingColor: "#db2777",
            headingBorder: "#7c3aed",
            subText: "#6b7280",
            skillBg: "#f5f3ff",
            skillText: "#6d28d9",
            skillBorder: "#c4b5fd",
            linkColor: "#db2777",
            accentColor: "#7c3aed",
            separatorColor: "#f3f4f6",
        },
    },
    {
        id: "split-diamond",
        name: "Diamond Split",
        description: "Silver & ice blue — luxury equal-column split",
        previewGradient: "linear-gradient(135deg, #0f172a 0%, #38bdf8 100%)",
        layout: "modern-split",
        colors: {
            headerBg: "#0f172a",
            headerText: "#ffffff",
            bodyBg: "#ffffff",
            bodyText: "#0f172a",
            headingColor: "#0f172a",
            headingBorder: "#38bdf8",
            subText: "#64748b",
            skillBg: "#f0f9ff",
            skillText: "#0369a1",
            skillBorder: "#38bdf8",
            linkColor: "#0284c7",
            accentColor: "#38bdf8",
            separatorColor: "#e0f2fe",
        },
    },

    // ── ELEGANT BORDER LAYOUT (top & bottom accent borders, single block header, 2-col body) ──
    {
        id: "border-gold-onyx",
        name: "Gold & Onyx",
        description: "Thick gold borders — premium black & gold elegance",
        previewGradient: "linear-gradient(to bottom, #D4AF37 4%, #000000 4%, #000000 50%, #ffffff 50%)",
        layout: "elegant-border",
        colors: {
            headerBg: "#000000",
            headerText: "#D4AF37",
            bodyBg: "#ffffff",
            bodyText: "#1a1a1a",
            headingColor: "#1a1a1a",
            headingBorder: "#D4AF37",
            subText: "#666666",
            skillBg: "rgba(212, 175, 55, 0.08)",
            skillText: "#1a1a1a",
            skillBorder: "#D4AF37",
            linkColor: "#D4AF37",
            accentColor: "#D4AF37",
            separatorColor: "#D4AF37",
        },
    },
    {
        id: "border-executive",
        name: "Executive Border",
        description: "High-contrast black border — commanding presence",
        previewGradient: "linear-gradient(to bottom, #111111 4%, #ffffff 4%)",
        layout: "elegant-border",
        colors: {
            headerBg: "#111111",
            headerText: "#ffffff",
            bodyBg: "#ffffff",
            bodyText: "#000000",
            headingColor: "#000000",
            headingBorder: "#111111",
            subText: "#4b5563",
            skillBg: "#f3f4f6",
            skillText: "#111111",
            skillBorder: "#d1d5db",
            linkColor: "#111111",
            accentColor: "#000000",
            separatorColor: "#e5e7eb",
        },
    },
    {
        id: "border-scholar",
        name: "Scholar Border",
        description: "Academic golden border — research & education focus",
        previewGradient: "linear-gradient(to bottom, #b45309 4%, #fef3c7 4%, #fef3c7 50%, #ffffff 50%)",
        layout: "elegant-border",
        colors: {
            headerBg: "#fef3c7",
            headerText: "#7c2d12",
            bodyBg: "#ffffff",
            bodyText: "#1c1917",
            headingColor: "#7c2d12",
            headingBorder: "#b45309",
            subText: "#78716c",
            skillBg: "#fffbeb",
            skillText: "#7c2d12",
            skillBorder: "#fcd34d",
            linkColor: "#9a3412",
            accentColor: "#b45309",
            separatorColor: "#fde68a",
        },
    },
    // ── GOLD STANDARD SPECIALS ──
    {
        id: "gold-minimal",
        name: "Minimal Gold",
        description: "Ultra-clean white & gold — minimal single-column",
        previewGradient: "linear-gradient(135deg, #ffffff 0%, #D4AF37 100%)",
        layout: "compact",
        colors: {
            headerBg: "#ffffff",
            headerText: "#000000",
            bodyBg: "#ffffff",
            bodyText: "#000000",
            headingColor: "#D4AF37",
            headingBorder: "#D4AF37",
            subText: "#666666",
            skillBg: "rgba(212, 175, 55, 0.05)",
            skillText: "#000000",
            skillBorder: "#D4AF37",
            linkColor: "#D4AF37",
            accentColor: "#D4AF37",
            separatorColor: "#f0f0f0",
        },
    },
    {
        id: "royal-gold-sidebar",
        name: "Royal Sidebar",
        description: "Deep charcoal sidebar with gold accents — creative & elite",
        previewGradient: "linear-gradient(to right, #1a1a1a 40%, #ffffff 40%)",
        layout: "sidebar-left",
        colors: {
            headerBg: "#1a1a1a",
            headerText: "#D4AF37",
            bodyBg: "#ffffff",
            bodyText: "#1a1a1a",
            headingColor: "#D4AF37",
            headingBorder: "#D4AF37",
            subText: "#4a4a4a",
            skillBg: "rgba(212, 175, 55, 0.1)",
            skillText: "#D4AF37",
            skillBorder: "#D4AF37",
            linkColor: "#D4AF37",
            accentColor: "#D4AF37",
            separatorColor: "#f0f0f0",
            sidebarBg: "#1a1a1a",
            sidebarText: "#ffffff",
        },
    },
    {
        id: "midnight-gold",
        name: "Midnight Gold",
        description: "Modern professional — dark-themed luxury",
        previewGradient: "linear-gradient(135deg, #000000 0%, #1a1a1a 100%)",
        layout: "modern-split",
        colors: {
            headerBg: "#000000",
            headerText: "#D4AF37",
            bodyBg: "#0a0a0a",
            bodyText: "#ffffff",
            headingColor: "#D4AF37",
            headingBorder: "#D4AF37",
            subText: "#a0a0a0",
            skillBg: "rgba(212, 175, 55, 0.15)",
            skillText: "#ffffff",
            skillBorder: "#D4AF37",
            linkColor: "#D4AF37",
            accentColor: "#D4AF37",
            separatorColor: "#1a1a1a",
        },
    },
    {
        id: "ats-gold",
        name: "ATS Gold",
        description: "ATS-optimized gold standard — simple & effective",
        previewGradient: "linear-gradient(135deg, #f8f9fa 0%, #D4AF37 100%)",
        layout: "classic",
        colors: {
            headerBg: "#ffffff",
            headerText: "#000000",
            bodyBg: "#ffffff",
            bodyText: "#000000",
            headingColor: "#D4AF37",
            headingBorder: "#D4AF37",
            subText: "#4b5563",
            skillBg: "#f3f4f6",
            skillText: "#1a1a1a",
            skillBorder: "#e5e7eb",
            linkColor: "#111111",
            accentColor: "#D4AF37",
            separatorColor: "#eeeeee",
        },
    },
];

export function getTemplateById(id: string): ResumeTemplateConfig {
    return RESUME_TEMPLATES.find((t) => t.id === id) || RESUME_TEMPLATES[0];
}
